[package]
name = "hc-reliability"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
ureq = { workspace = true }
