name: ReleaseLinuxX64
on:
  workflow_dispatch:
jobs:
  release-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Version
        id: version
        run: |
          VER=$(grep version Cargo.toml | head -1 | cut -d '"' -f 2)
          echo SETTING VERSION ${VER}
          echo "version=${VER}" >> $GITHUB_OUTPUT

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          tags: dockbuildrust:latest
          context: docker/ui-release
          push: false

      - name: Build Executable
        uses: addnab/docker-run-action@v3
        with:
          image: dockbuildrust:latest
          options: -v ${{ github.workspace }}:/work
          run: |
            /root/.cargo/bin/cargo build --release
            cd target/release
            mv hc-reliability ../../hc-reliability-linux-x64-${{ steps.version.outputs.version }}

      - name: Zip Executable
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: zip
          filename: hc-reliability-linux-x64-${{ steps.version.outputs.version }}.zip
          path: hc-reliability-linux-x64-${{ steps.version.outputs.version }}

      - name: Publish Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hc-reliability-linux-x64-${{ steps.version.outputs.version }}.zip
          asset_name: hc-reliability
          tag: "v${{ steps.version.outputs.version }}"
          overwrite: true
          body: "hc-reliability release v${{ steps.version.outputs.version }}"
