name: ReliabilityBuild
on:
  workflow_dispatch:
jobs:
  reliability-build:
    runs-on: ubuntu-latest
    container:
      image: dockbuild/ubuntu1604:latest
    steps:
      #      - name: Checkout code
      #        run: git clone --depth=1 https://github.com/holochain/reliability.git

      #      - name: Print Glibc Version
      # run: ldd --version ldd

          #      - name: Install Rust
          #        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile minimal -y

          #      - name: Build reliability
          #        run: |
          #          cd reliability
          #          PATH=~/.cargo/bin:$(pwd)/go/bin:$PATH cargo build --release

          #      - name: Print reliability ldd
          #        run: ldd reliability/target/release/reliability

      - name: install jq
        run: |
          apt update
          apt install -y jq

      - name: Create Release
        run: |
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ github.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/holochain/reliability/releases -d '{"tag_name":"v0.0.1","target_commitish":"main","name":"v0.0.1","body":"Release v0.0.1","draft":false,"prerelease":false,"generate_release_notes":false}' | tee | jq .id >> release.id
          echo PRINTING RELEASE ID
          cat release.id

      #      - name: Upload Artifact
      #        run: |
      #          echo "test" > bob.txt
      #          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer <YOUR-TOKEN>" -H "X-GitHub-Api-Version: 2022-11-28" -H "Content-Type: application/octet-stream" "https://uploads.github.com/repos/holochain/reliability/releases/RELEASE_ID/assets?name=example.zip" \
  --data-binary "@example.zip"
