name: UiRelease2LinuxX64
on:
  workflow_dispatch:
jobs:
  ui-release-2-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          tags: dockbuildrust:latest
          context: docker/ui-release
          push: false

      - name: Build Executable
        uses: addnab/docker-run-action@v3
        with:
          image: dockbuildrust:latest
          options: -v ${{ github.workspace }}:/work
          run: /root/.cargo/bin/cargo build --release --manifest-path hc-reliability-ui/Cargo.toml
